### ISSUE TITLE
Capture the exception in `assert_raise`

### ISSUE THREAD

**Issue by foca** [emancu/crotest#5]
It would be useful to capture the exception in an `assert_raise` to test the message is the expected one. I'm testing the responses of a library that might return several different errors using the same subclass of `Exception`, and I would like to make sure the `err.message` is the one I should be getting.

Not sure if this is doable with Crystal macros as I haven't really delved into that yet.

**Comment by emancu** [comment]
Interesting, I will take a look tonight and see what can I do.
